module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    'home',
    {
      type: 'category',
      label: 'Useful links',
      items: [
        { type: 'link', label: 'Website', href: 'https://dashboard.olympusgg.com', },
        { type: 'link', label: 'Discord', href: 'https://discord.com/olympusgg', }
      ]
    },
    {
      type: 'category',
      label: 'Custom Features',
      items: [
        { type: 'doc', id: 'custom-features/achievements', label: 'Achievements' },
        { type: 'doc', id: 'custom-features/pocket-dimensions', label: 'Pocket Dimensions' },
        { type: 'doc', id: 'custom-features/loyalty-system', label: 'Loyalty System' },
      ]
    },
    {
      type: 'category',
      label: 'Quality Of Life',
      items: [
        { type: 'doc', id: 'qol/exploration', label: 'Exploration' },
        { type: 'doc', id: 'qol/mass-crafting', label: 'Mass Crafting' },
        { type: 'doc', id: 'qol/upgrades', label: 'Upgrades' },
      ]
    },
    {
      type: 'category',
      label: 'Drops',
      items: [
        {
          type: 'category',
          label: 'Item drops',
          items: [
            {
              type: 'autogenerated',
              dirName: 'drops/items'
            }
          ]
        },
        {
          type: 'category',
          label: 'Map drops',
          items: [
            {
              type: 'autogenerated',
              dirName: 'drops/maps'
            }
          ]
        },
      ]
    }
  ]

};
